const contentGenerator = {
    attention: {
        prefix: [
            "STOP!", "WOW!", "PERHATIAN!", "HOT ITEM!", "NEW ARRIVAL!", 
            "LIMITED!", "EXCLUSIVE!", "VIRAL!", "TRENDING!", "BEST SELLER!",
            "GRAB IT!", "BURUAN!", "CEK INI!", "RECOMMENDED!", "MUST HAVE!",
            "SUPER DEAL!", "SPECIAL!", "TOP ITEM!", "FAVORITE!", "POPULER!",
            "BOOM!", "ALERT!", "HARUS PUNYA!", "GAK NYESEL!", "WORTH IT!",
            "LARIS!", "TERLARIS!", "HITS!", "KEREN!", "MANTAP!",
            "BEST PRICE!", "FLASH DEAL!", "READY STOCK!", "RESTOCK!", "BACK IN STOCK!",
            "PROMO SPESIAL!", "DISKON GEDE!", "HARGA GILA!", "OBRAL!", "CUCI GUDANG!",
            "SHOCKING PRICE!", "HARGA TERJUN!", "SPECIAL OFFER!", "MEGA SALE!", "BIG DEAL!",
            "HARGA PROMO!", "DISKON HEBOH!", "SALE BESAR!", "SPECIAL PRICE!", "HARGA SPESIAL!",
            "SUPER HOT!", "LUAR BIASA!", "SPEKTAKULER!", "FENOMENAL!", "SENSASIONAL!",
            "INCREDIBLE!", "FANTASTIC!", "AMAZING!", "EXTRAORDINARY!", "REMARKABLE!",
            "TERBAIK!", "TERMURAH!", "TERLENGKAP!", "TERPERCAYA!", "TERJAMIN!",
            "SUPER SALE!", "MEGA DEAL!", "BIG PROMO!", "SPECIAL PRICE!", "HARGA GILA!",
            "FLASH SALE!", "CRAZY DEAL!", "SUPER DISKON!", "HARGA SPESIAL!", "PROMO GILA!",
            "PROMO SPESIAL HARI INI",
            "FLASH SALE TERBATAS",
            "DISKON BESAR BESARAN",
            "HARGA TERMURAH SEPANJANG MASA",
            "STOK TERBATAS BULAN INI",
            "PROMO CUCI GUDANG",
            "SPECIAL PRICE",
            "NEW ARRIVAL",
            "BEST DEAL",
            "SUPER SALE",
            "MEGA SALE",
            "BIG SALE",
            "SPECIAL OFFER",
            "LIMITED STOCK",
            "EXCLUSIVE DEAL",
            "SPECIAL EDITION",
            "PREMIUM QUALITY",
            "READY STOCK",
            "HARGA GROSIR",
            "PROMO MINGGU INI",
            "DISKON SPESIAL",
            "HARGA TERBAIK",
            "PROMO TERBATAS",
            "SPECIAL PRICE",
            "HARGA PROMO",
            "HARGA SPECIAL",
            "HARGA HEMAT",
            "PROMO HEBOH",
            "DISKON GILA",
            "OBRAL BESAR",
            "CUCI GUDANG",
            "PROMO LEBARAN",
            "PROMO RAMADHAN",
            "PROMO TAHUN BARU",
            "PROMO NATAL",
            "PROMO IMLEK",
            "PROMO AKHIR TAHUN",
            "PROMO AKHIR BULAN",
            "PROMO WEEKEND",
            "PROMO MINGGUAN",
            "PROMO BULANAN",
            "HARGA TERJANGKAU",
            "HARGA BERSAHABAT",
            "HARGA EKONOMIS",
            "HARGA TERMURAH",
            "HARGA GROSIR",
            "HARGA RESELLER",
            "HARGA DISTRIBUTOR",
            "HARGA SPECIAL AGEN",
            "PROMO MEMBER",
            "PROMO KHUSUS",
            "SPECIAL DISCOUNT",
            "BIG DISCOUNT",
            "MEGA DISCOUNT",
            "SUPER DISCOUNT",
            "SPECIAL PRICE",
            "BEST PRICE",
            "LOW PRICE",
            "FACTORY PRICE",
            "WHOLESALE PRICE",
            "RETAIL PRICE",
            "SPECIAL OFFER",
            "LIMITED OFFER",
            "EXCLUSIVE OFFER",
            "SPECIAL PROMOTION",
            "HOT PROMOTION",
            "BIG PROMOTION",
            "MEGA PROMOTION",
            "SUPER PROMOTION",
            "SPECIAL DEAL",
            "HOT DEAL",
            "BIG DEAL",
            "MEGA DEAL",
            "SUPER DEAL",
            "BEST DEAL",
            "SPECIAL PACKAGE",
            "COMBO PACKAGE",
            "HEMAT PACKAGE",
            "BUNDLE PACKAGE",
            "VALUE PACKAGE",
            "PREMIUM PACKAGE",
            "EXCLUSIVE PACKAGE",
            "LIMITED PACKAGE",
            "SPECIAL BUNDLE",
            "COMBO BUNDLE",
            "HEMAT BUNDLE",
            "VALUE BUNDLE",
            "PREMIUM BUNDLE",
            "EXCLUSIVE BUNDLE",
            "LIMITED BUNDLE",
            "PROMO SPESIAL RAMADHAN!",
            "PROMO SPESIAL LEBARAN!",
            "PROMO SPESIAL TAHUN BARU!",
            "PROMO SPESIAL IMLEK!",
            "PROMO SPESIAL NATAL!",
            "PROMO SPESIAL HARBOLNAS!",
            "PROMO SPESIAL 11.11!",
            "PROMO SPESIAL 12.12!",
            "PROMO SPESIAL WEEKEND!",
            "PROMO SPESIAL GAJIAN!",
            "PROMO SPESIAL ULTAH!",
            "PROMO SPESIAL ANNIVERSARY!",
            "PROMO SPESIAL GRAND OPENING!",
            "PROMO SPESIAL GRAND CLOSING!",
            "PROMO SPESIAL RELOKASI!",
            "PROMO SPESIAL RENOVASI!",
            "PROMO SPESIAL CUCI GUDANG!",
            "PROMO SPESIAL CLEARANCE!",
            "PROMO SPESIAL END YEAR!",
            "PROMO SPESIAL NEW YEAR!"
        ],
        suffix: [
            "Koleksi Terbaru Sudah Hadir!",
            "Jangan Sampai Kehabisan!",
            "Buruan Sebelum Sold Out!",
            "Yang Ditunggu-tunggu Akhirnya Datang!",
            "Promo Spesial Hari Ini!",
            "Diskon Terbatas!",
            "Harga Special!",
            "Flash Sale!",
            "Stok Terbatas!",
            "Promo Minggu Ini!",
            "Harga Termurah Sepanjang Masa!",
            "Potongan Harga Gila-gilaan!",
            "Diskon Spesial Akhir Bulan!",
            "Promo Cuci Gudang!",
            "Sale Besar-besaran!",
            "Harga Hancur!",
            "Promo Terbatas!",
            "Diskon Mengejutkan!",
            "Harga Spesial Untukmu!",
            "Promo Yang Ditunggu-tunggu!",
            "Kesempatan Terbatas Hari Ini!",
            "Promo Kilat 24 Jam!",
            "Diskon Spesial Member!",
            "Harga Terendah Bulan Ini!",
            "Promo Khusus Followers!",
            "Diskon Spesial Weekend!",
            "Harga Promo Terbatas!",
            "Special Price Today Only!",
            "Mega Sale Minggu Ini!",
            "Promo Spesial Lebaran!",
            "Kesempatan Emas Hari Ini!",
            "Promo Spesial Bulan Ini!",
            "Diskon Besar-Besaran!",
            "Harga Termurah Sejabodetabek!",
            "Promo Terbatas Minggu Ini!",
            "Diskon Menggiurkan!",
            "Harga Miring Banget!",
            "Promo Gila-Gilaan!",
            "Diskon Fantastis!",
            "Harga Bombastis!",
            "Promo Super Hemat!",
            "Diskon Dahsyat!",
            "Harga Merakyat!",
            "Promo Spektakuler!",
            "Diskon Sensasional!",
            "Hanya Hari Ini!",
            "Sampai Hari Ini!",
            "Segera Dapatkan!",
            "Jangan Tunda Lagi!",
            "Ambil Sekarang!",
            "Pesan Sekarang!",
            "Order Sekarang!",
            "Beli Sekarang!",
            "Dapatkan Sekarang!",
            "Miliki Sekarang!",
            "Segera Miliki!",
            "Segera Order!",
            "Segera Pesan!",
            "Segera Beli!",
            "Buruan Order!",
            "Buruan Pesan!",
            "Buruan Beli!",
            "Buruan Ambil!",
            "Jangan Ketinggalan!",
            "Jangan Sampai Habis!",
            "Sebelum Kehabisan!",
            "Sebelum Terlambat!",
            "Selagi Ada!",
            "Selagi Stok Ada!",
            "Selagi Masih Ada!",
            "Stok Terbatas!",
            "Persediaan Terbatas!",
            "Limited Stock!",
            "Ready Stock!",
            "Best Seller!",
            "Paling Laris!",
            "Terlaris!",
            "Terpopuler!",
            "Termurah!",
            "Terjangkau!",
            "Berkualitas!",
            "Terpercaya!",
            "Terjamin!",
            "Bergaransi!",
            "Original!",
            "Asli!",
            "Premium!",
            "Exclusive!",
            "Special!",
            "Limited!",
            "New!",
            "Hot!",
            "Trending!",
            "Viral!",
            "Recommended!",
            "Must Have!",
            "Best Choice!",
            "Best Quality!",
            "High Quality!",
            "Top Quality!",
            "Premium Quality!",
            "Exclusive Quality!",
            "Special Quality!",
            "Limited Quality!",
            "Best Price!",
            "Best Deal!",
            "Best Offer!",
            "Special Price!",
            "Special Deal!",
            "Special Offer!",
            "Limited Price!",
            "Limited Deal!",
            "Limited Offer!",
            "Harga Grosir!",
            "Harga Reseller!",
            "Harga Distributor!",
            "Harga Agen!",
            "Harga Member!",
            "Harga Spesial!",
            "Harga Khusus!",
            "Harga Terbaik!",
            "Harga Termurah!",
            "Harga Terjangkau!",
            "Harga Bersahabat!",
            "Harga Ekonomis!",
            "Harga Hemat!",
            "Harga Promo!",
            "Harga Diskon!",
            "Harga Obral!",
            "Harga Cuci Gudang!",
            "Promo Terbatas!",
            "Diskon Terbatas!",
            "Obral Terbatas!",
            "Cuci Gudang Terbatas!",
            "Promo Terbatas Hari Ini Saja!",
            "Promo Spesial Minggu Ini!",
            "Promo Khusus Member!",
            "Promo Ekslusif Followers!",
            "Promo Spesial Subscriber!",
            "Promo Terbatas 100 Pembeli Pertama!",
            "Promo Flash Sale 1 Jam!",
            "Promo Kilat 24 Jam!",
            "Promo Terbatas Stock Ready!",
            "Promo Spesial Free Ongkir!"
        ]
    },
    interest: {
        prefix: [
            "Mau tampil keren?",
            "Upgrade penampilanmu dengan",
            "Tampil PD dengan",
            "Jadi pusat perhatian dengan",
            "Level up style-mu pakai",
            "Bikin aura-mu makin terpancar dengan",
            "Tingkatkan kepercayaan dirimu dengan",
            "Tampil beda dengan",
            "Makin stunning dengan",
            "Jadi trendsetter dengan",
            "Gak mau ketinggalan trend?",
            "Pengen tampil beda?",
            "Mau jadi yang pertama?",
            "Ingin tampil maksimal?",
            "Siap-siap jadi sorotan dengan",
            "Bikin semua mata tertuju padamu dengan",
            "Tampil memukau dengan",
            "Jadi yang paling hits dengan",
            "Upgrade gayamu dengan",
            "Siap mencuri perhatian dengan",
            "Mau hemat budget?",
            "Butuh produk berkualitas?",
            "Cari barang original?",
            "Mau dapat yang terbaik?",
            "Cari kualitas premium?",
            "Pengen produk terlaris?",
            "Butuh barang branded?",
            "Mau dapat yang asli?",
            "Cari produk limited?",
            "Ingin tampil beda?",
            "Mau jadi trendsetter?",
            "Pengen gaya kekinian?",
            "Butuh produk berkualitas?",
            "Cari barang premium?",
            "Mau hemat tapi berkualitas?",
            "Ingin produk terbaik?",
            "Cari kualitas terjamin?",
            "Butuh yang original?",
            "Mau dapat yang asli?",
            "Pengen tampil maksimal?",
            "Ingin jadi pusat perhatian?",
            "Mau gaya up to date?",
            "Butuh yang terpercaya?",
            "Cari yang recommended?",
            "Mau hemat belanja?",
            "Mau dapat harga terbaik?",
            "Mau dapat kualitas premium?",
            "Mau tampil beda?",
            "Mau jadi pusat perhatian?",
            "Mau upgrade penampilan?",
            "Mau gaya kekinian?",
            "Mau tampil hits?",
            "Mau dapat barang branded?",
            "Mau dapat produk original?"
        ],
        middle: [
            "yang hadir dengan",
            "yang dilengkapi",
            "yang didesain dengan",
            "yang dibuat khusus dengan",
            "yang diproduksi dengan",
            "yang dirancang dengan",
            "yang hadir spesial dengan",
            "yang tampil dengan",
            "yang memberikan",
            "yang menghadirkan",
            "yang menawarkan",
            "yang dipersembahkan dengan",
            "yang dihadirkan dengan",
            "yang diciptakan dengan",
            "yang dikembangkan dengan",
            "yang dibuat dengan",
            "yang dipersiapkan dengan",
            "yang dipilih dengan",
            "yang disempurnakan dengan",
            "yang diluncurkan dengan",
            "yang terjamin dengan",
            "yang terkenal dengan",
            "yang populer dengan",
            "yang best seller dengan",
            "yang recommended dengan",
            "yang terpercaya dengan",
            "yang berkualitas dengan",
            "yang terbaik dengan",
            "yang original dengan",
            "yang authentic dengan",
            "yang dipersembahkan dengan",
            "yang didesain khusus dengan",
            "yang dibuat spesial dengan",
            "yang diproduksi dengan",
            "yang dirancang dengan",
            "yang dikembangkan dengan",
            "yang disiapkan dengan",
            "yang dihadirkan dengan",
            "yang diciptakan dengan",
            "yang dipersiapkan dengan",
            "yang disempurnakan dengan",
            "yang dipilih dengan",
            "yang diseleksi dengan",
            "yang diolah dengan",
            "yang diproses dengan",
            "yang diproduksi khusus dengan",
            "yang dibuat limited edition dengan",
            "yang dirancang spesial dengan",
            "yang didesain eksklusif dengan",
            "yang dipilih khusus dengan",
            "yang disiapkan spesial dengan",
            "yang dihadirkan eksklusif dengan",
            "yang diciptakan khusus dengan",
            "yang dikembangkan spesial dengan",
            "yang dipersiapkan eksklusif dengan"
        ],
        suffix: [
            "kualitas premium!",
            "desain eksklusif!",
            "bahan terbaik!",
            "teknologi terkini!",
            "standar internasional!",
            "sentuhan modern!",
            "detail sempurna!",
            "inovasi terbaru!",
            "keunggulan spesial!",
            "fitur terbaik!",
            "kualitas terjamin!",
            "desain memukau!",
            "bahan pilihan!",
            "teknologi canggih!",
            "standar kualitas tinggi!",
            "sentuhan elegan!",
            "detail mewah!",
            "inovasi mutakhir!",
            "keunggulan tersendiri!",
            "fitur unggulan!",
            "garansi terpercaya!",
            "kualitas internasional!",
            "standar premium!",
            "hasil maksimal!",
            "performa terbaik!",
            "kualitas terjaga!",
            "hasil optimal!",
            "standar tinggi!",
            "kualitas superior!",
            "hasil memuaskan!",
            "kualitas super!",
            "standar premium!",
            "teknologi modern!",
            "inovasi terkini!",
            "desain eksklusif!",
            "material terbaik!",
            "hasil maksimal!",
            "performa optimal!",
            "kualitas unggulan!",
            "standar internasional!",
            "teknologi canggih!",
            "inovasi mutakhir!",
            "desain memukau!",
            "material pilihan!",
            "hasil sempurna!",
            "kualitas premium!",
            "bahan terbaik!",
            "desain eksklusif!",
            "model terbaru!",
            "teknologi terkini!",
            "fitur canggih!",
            "spesifikasi lengkap!",
            "garansi resmi!",
            "sertifikat asli!",
            "standar internasional!"
        ]
    },
    desire: {
        prefix: [
            "Keunggulan produk:",
            "Yang bikin spesial:",
            "Kenapa harus punya:",
            "Fitur unggulan:",
            "Kelebihan produk:",
            "Benefits yang didapat:",
            "Value yang ditawarkan:",
            "Keistimewaan produk:",
            "Mengapa produk ini berbeda:",
            "Apa yang kamu dapatkan:",
            "Keunikan produk:",
            "Yang membuat berbeda:",
            "Benefit spesial:",
            "Nilai lebih produk:",
            "Kenapa produk ini:",
            "Alasan harus punya:",
            "Kualitas unggulan:",
            "Spesifikasi premium:",
            "Fitur terbaik:",
            "Keunggulan utama:",
            "Benefit yang didapat:",
            "Kelebihan utama:",
            "Point plus produk:",
            "Nilai tambah produk:",
            "Keunggulan khusus:",
            "Special features:",
            "Kualitas premium:",
            "Benefit exclusive:",
            "Keistimewaan khusus:",
            "Value added:"
        ],
        features: {
            fashion: [
                "Bahan premium selected",
                "Jahitan rapi & kuat",
                "Design timeless",
                "Nyaman dipakai",
                "Size lengkap",
                "Model versatile",
                "Cutting presisi",
                "Anti kusut",
                "Tidak mudah luntur",
                "Bahan adem",
                "Bahan import premium",
                "Jahitan double stitch",
                "Design exclusive",
                "Nyaman seharian",
                "Size chart lengkap",
                "Model multifungsi",
                "Cutting modern",
                "Anti gerah",
                "Warna tahan lama",
                "Bahan halus",
                "Bahan premium import",
                "Quality control ketat",
                "Design limited edition",
                "Jahitan presisi",
                "Material berkualitas",
                "Style update",
                "Trend terkini",
                "Model exclusive",
                "Detail sempurna",
                "Finishing premium",
                "Bahan premium selected",
                "Design limited edition",
                "Cutting modern style",
                "Jahitan presisi tinggi",
                "Model exclusive",
                "Bahan import premium",
                "Design trendy",
                "Cutting perfect fit",
                "Jahitan rapi & kuat",
                "Model versatile",
                "Bahan berkualitas tinggi",
                "Design timeless",
                "Cutting ergonomis",
                "Jahitan double stitch",
                "Model update"
            ],
            beauty: [
                "Bahan alami",
                "Sudah BPOM",
                "Hasil maksimal",
                "Aman dipakai",
                "Tidak lengket",
                "Tahan lama",
                "Ringan di kulit",
                "Wangi tahan lama",
                "Tidak menyebabkan iritasi",
                "Cepat menyerap",
                "Ekstrak natural",
                "Sertifikasi halal",
                "Hasil instan",
                "Dermatologically tested",
                "Tekstur ringan",
                "Long lasting",
                "Cocok semua kulit",
                "Aroma therapeutic",
                "Hypoallergenic",
                "Fast absorbing",
                "Formula terbaru",
                "Bahan organik",
                "Teruji klinis",
                "Hasil permanen",
                "Efek instan",
                "Kandungan alami",
                "Tidak berbahaya",
                "Aman untuk semua",
                "Hasil maksimal",
                "Efek tahan lama",
                "Formula Korea",
                "Teknologi Jepang",
                "Standar FDA",
                "Clinical Tested",
                "Dermatologist Tested",
                "Hypoallergenic",
                "Non-Comedogenic",
                "Paraben Free",
                "Fragrance Free",
                "Alcohol Free",
                "Natural Ingredients",
                "Organic Certified",
                "Vegan Friendly",
                "Cruelty Free",
                "Eco Friendly"
            ],
            electronics: [
                "Garansi resmi",
                "Hemat energi",
                "Performa tinggi",
                "Fitur lengkap",
                "Build quality premium",
                "Fast charging",
                "Tahan lama",
                "After sales terjamin",
                "Original 100%",
                "Teknologi terbaru",
                "Garansi international",
                "Power efficient",
                "High performance",
                "Feature packed",
                "Premium build",
                "Quick charge",
                "Long lasting battery",
                "Service center resmi",
                "Authentic product",
                "Latest technology",
                "Smart features",
                "AI technology",
                "Energy saving",
                "Easy to use",
                "Multi-function",
                "Advanced system",
                "User friendly",
                "High durability",
                "Modern design",
                "Latest innovation",
                "Smart Technology",
                "AI Powered",
                "Energy Efficient",
                "Fast Processing",
                "High Performance",
                "Premium Quality",
                "Latest Innovation",
                "Advanced Features",
                "Smart Integration",
                "Voice Control",
                "Touch Screen",
                "Wireless Technology",
                "Bluetooth 5.0",
                "Quick Response",
                "HD Display"
            ],
            food: [
                "100% Halal",
                "Bahan berkualitas",
                "Rasa authentic",
                "Fresh ingredients",
                "No pengawet",
                "Higienis terjamin",
                "Proses steril",
                "Quality check",
                "Kemasan aman",
                "Best ingredients",
                "Rasa premium",
                "Natural taste",
                "Resep original",
                "Tanpa MSG",
                "Food grade",
                "Standar BPOM",
                "Sertifikasi MUI",
                "Quality control",
                "Fresh daily",
                "Hygiene certified",
                "100% Fresh Daily",
                "Bahan Premium Selected",
                "Rasa Otentik",
                "Kemasan Food Grade",
                "Proses Higienis",
                "Standar HACCP",
                "Quality Control Ketat",
                "Sertifikasi ISO",
                "Dapur Bersertifikat",
                "Bahan Import",
                "Chef Berpengalaman",
                "Menu Signature",
                "Resep Turun Temurun",
                "Bumbu Rahasia",
                "Teknik Modern",
                "Fusion Style",
                "Porsi Jumbo",
                "Packaging Premium",
                "Express Delivery",
                "Fresh Cooking",
                "Best Ingredients",
                "Premium Quality",
                "Authentic Recipe",
                "Special Menu",
                "Limited Menu"
            ],
            health: [
                "BPOM Approved",
                "Halal certified",
                "Clinical tested",
                "Doctor recommended",
                "Natural ingredients",
                "No side effects",
                "Fast results",
                "Safe to consume",
                "Quality assured",
                "Lab tested",
                "GMP certified",
                "ISO standard",
                "Pure natural",
                "Scientifically proven",
                "Expert choice",
                "Premium quality",
                "Internationally approved",
                "Research based",
                "Medical grade",
                "Health standard",
                "Teruji Klinis",
                "Rekomendasi Dokter",
                "Standar WHO",
                "Sertifikasi FDA",
                "Bahan Alami",
                "Herbal Premium",
                "Ekstrak Pilihan",
                "Formula Khusus",
                "Teknologi Swiss",
                "Riset 10 Tahun",
                "Patent Formula",
                "Quality Control",
                "Lab Tested",
                "Hasil Maksimal",
                "Aman Dikonsumsi",
                "Efek Cepat",
                "Tanpa Efek Samping",
                "Money Back Guarantee",
                "Testimoni Positif",
                "Review Terpercaya",
                "Rekomendasi Ahli",
                "Standar Internasional",
                "Kualitas Premium",
                "Hasil Permanen",
                "Garansi Uang Kembali"
            ],
            sports: [
                "High performance",
                "Durability tested",
                "Pro quality",
                "Competition grade",
                "Premium material",
                "Ergonomic design",
                "Comfort fit",
                "Professional choice",
                "Athletic standard",
                "Sport specific",
                "Advanced tech",
                "Breathable material",
                "Flexible design",
                "Impact protection",
                "Weather resistant",
                "Quick dry",
                "Anti slip",
                "Lightweight",
                "Extra support",
                "Maximum comfort",
                "Pro Quality",
                "Competition Grade",
                "Premium Material",
                "Ergonomic Design",
                "Maximum Comfort",
                "Performance Boost",
                "Injury Prevention",
                "Moisture Wicking",
                "Breathable Fabric",
                "Anti-Slip Grip",
                "Shock Absorption",
                "Flexible Movement",
                "Durable Construction",
                "Weather Resistant",
                "UV Protection",
                "Quick Dry Technology",
                "Lightweight Design",
                "Professional Choice",
                "Tournament Ready",
                "Training Optimized",
                "Match Quality",
                "Elite Performance",
                "Competition Ready",
                "Premium Selection",
                "Expert Recommended"
            ],
            toys: [
                "Bahan aman untuk anak",
                "Sertifikasi SNI",
                "Edukasi sambil bermain",
                "Merangsang kreativitas",
                "Melatih motorik",
                "Bahan non-toxic",
                "Mudah dibersihkan",
                "Desain menarik",
                "Warna cerah",
                "Ukuran pas",
                "Recommended age",
                "Multiple functions",
                "Easy to assemble",
                "Portable design",
                "Durable material",
                "Educational value",
                "Interactive features",
                "Safe edges",
                "Quality checked",
                "Parent approved"
            ],
            stationery: [
                "Kualitas premium",
                "Tinta tidak mudah luntur",
                "Desain ergonomis",
                "Grip nyaman",
                "Hasil tulisan rapi",
                "Tidak mudah patah",
                "Warna konsisten",
                "Ketebalan pas",
                "Material berkualitas",
                "Awet digunakan",
                "Multi-function",
                "Smooth writing",
                "Quick dry ink",
                "No smudge",
                "Precision tip",
                "Color variety",
                "Long lasting",
                "Easy to carry",
                "Professional look",
                "Value for money"
            ],
            music: [
                "Kualitas suara premium",
                "Material berkualitas",
                "Tone akurat",
                "Build quality terbaik",
                "Finishing sempurna",
                "Setup presisi",
                "Original product",
                "Professional grade",
                "Studio quality",
                "Perfect tuning",
                "Rich sound",
                "Clear tone",
                "Balanced output",
                "Pro features",
                "Easy maintenance",
                "Durability tested",
                "Performance ready",
                "Stage worthy",
                "Recording quality",
                "Premium components"
            ],
            books: [
                "Kertas berkualitas",
                "Cetakan jelas",
                "Cover premium",
                "Binding kuat",
                "Font readable",
                "Konten lengkap",
                "Layout rapi",
                "Edisi terbaru",
                "Full color",
                "Bonus konten",
                "High quality print",
                "Premium paper",
                "Durable cover",
                "Perfect binding",
                "Clear typography",
                "Complete index",
                "Professional layout",
                "Updated content",
                "Extra materials",
                "Special edition"
            ],
            pets: [
                "Bahan food grade",
                "Aman untuk hewan",
                "Kualitas premium",
                "Mudah dibersihkan",
                "Desain ergonomis",
                "Nyaman digunakan",
                "Tahan lama",
                "Anti bacterial",
                "Higienis",
                "Size variatif",
                "Vet approved",
                "Easy to clean",
                "Durable material",
                "Pet friendly",
                "Quality tested",
                "Safe material",
                "Comfort design",
                "Multi-function",
                "Easy storage",
                "Premium quality"
            ]
        }
    },
    action: {
        prefix: [
            "Buruan order sekarang:",
            "Jangan sampai kehabisan:",
            "Segera checkout:",
            "Pesan sekarang juga:",
            "Order sebelum kehabisan:",
            "Dapatkan sekarang:",
            "Miliki sekarang juga:",
            "Jangan tunda lagi:",
            "Checkout sekarang:",
            "Klik link dibawah:",
            "Order langsung:",
            "Beli sekarang:",
            "Dapatkan segera:",
            "Ambil kesempatan ini:",
            "Jangan lewatkan:",
            "Segera miliki:",
            "Pesan langsung:",
            "Grab it fast:",
            "Add to cart sekarang:",
            "Klik untuk order:",
            "Pesan via link:",
            "Order via:",
            "Beli lewat:",
            "Shop now:",
            "Get it now:",
            "Purchase here:",
            "Buy now:",
            "Order now:",
            "Checkout here:",
            "Get yours:",
            "Order via link:",
            "Pesan sekarang:",
            "Dapatkan disini:",
            "Beli sekarang:",
            "Checkout disini:",
            "Klik untuk order:",
            "Pesan langsung:",
            "Dapatkan segera:",
            "Beli langsung:",
            "Order cepat:",
            "Pesan via:",
            "Dapatkan di:",
            "Beli di:",
            "Checkout via:",
            "Klik link:",
            "Yuk order sekarang:",
            "Yuk checkout sekarang:",
            "Yuk belanja sekarang:",
            "Yuk pesan sekarang:",
            "Langsung order disini:",
            "Langsung checkout disini:",
            "Langsung belanja disini:",
            "Langsung pesan disini:",
            "Buruan order via:",
            "Buruan checkout via:"
        ],
        suffix: [
            "Stok terbatas!",
            "Promo akan berakhir!",
            "Harga bisa naik sewaktu-waktu!",
            "Jangan sampai kelewatan!",
            "Kesempatan terbatas!",
            "Sebelum sold out!",
            "Sebelum diborong yang lain!",
            "Promo spesial hari ini!",
            "Bonus menarik menanti!",
            "Free ongkir!",
            "Stok hampir habis!",
            "Promo terbatas!",
            "Harga naik besok!",
            "Jangan sampai menyesal!",
            "Kesempatan emas!",
            "Sebelum kehabisan!",
            "Sebelum diborong yang lain!",
            "Special offer hari ini!",
            "Bonus spesial menanti!",
            "Gratis ongkir!",
            "Potongan harga spesial!",
            "Bonus hadiah menarik!",
            "Cashback melimpah!",
            "Diskon member!",
            "Extra bonus!",
            "Special gift!",
            "Voucher diskon!",
            "Hadiah langsung!",
            "Point reward!",
            "Free gift!",
            "Promo terbatas!",
            "Stok menipis!",
            "Harga naik besok!",
            "Diskon berakhir hari ini!",
            "Bonus melimpah!",
            "Cashback spesial!",
            "Free shipping!",
            "Gratis ongkir!",
            "Bonus ekstra!",
            "Hadiah langsung!",
            "Point rewards!",
            "Voucher diskon!",
            "Special gift!",
            "Extra bonus!",
            "Member discount!",
            "Jangan sampai kelewatan promonya!",
            "Jangan sampai kehabisan stocknya!",
            "Jangan sampai ketinggalan trendnya!",
            "Jangan sampai menyesal nantinya!",
            "Kesempatan terbatas hari ini!",
            "Promo kilat 24 jam saja!",
            "Stock ready terbatas!",
            "Free ongkir terbatas!",
            "Bonus spesial menanti!",
            "Hadiah menarik menanti!"
        ]
    },
    hashtags: {
        fashion: [
            "#fashion #ootd #style #fashionista",
            "#fashionstyle #fashionblogger #fashionable",
            "#fashionweek #fashiongram #fashionph",
            "#fashionpria #fashionwanita #fashionmuslim",
            "#fashionhijab #fashionkorea #fashionjapan",
            "#fashionbaju #fashiontas #fashionsepatu",
            "#fashionphotography #fashiondesigner #fashionmodel",
            "#fashionshow #fashionlover #fashiondiaries",
            "#fashiondaily #fashioninspo #fashioninspiration",
            "#fashionbrand #fashionstore #fashionshop",
            "#fashiontrend #fashionupdate #fashiontips",
            "#fashiongoals #fashionideas #fashionootd",
            "#fashionindo #fashionindonesia #fashionjakarta",
            "#fashionbandung #fashionsurabaya #fashionbali",
            "#fashionmalang #fashionsemarang #fashionmedan",
            "#fashionbatam #fashionpalembang #fashionmakassar",
            "#fashionpekanbaru #fashionpadang #fashionmanado",
            "#fashionbalikpapan #fashionpontianak #fashionambon",
            "#fashionlampung #fashionjambi #fashionbengkulu",
            "#fashionaceh #fashionriau #fashionbanten"
        ],
        beauty: [
            "#beauty #makeup #skincare #beautyblogger",
            "#beautytips #beautycare #beautygram",
            "#beautyaddict #beautyproducts #beautyjunkie",
            "#beautycommunity #beautyinfluencer #beautyvlogger",
            "#beautyreview #beautyfavorites #beautyessentials",
            "#beautyroutine #beautyregimen #beautysecrets",
            "#beautyindonesia #cantik #perawatan",
            "#kecantikan #kosmetik #makeupnatural",
            "#makeuplover #makeupjunkie #makeuptutorial",
            "#makeupideas #makeuplook #makeupgoals",
            "#skincarekorea #skincarejepang #skincarehalal",
            "#skincaremurah #skincarealami #skincareaman",
            "#skincarebpom #skincaremalam #skincarepagi",
            "#skincarewajah #skincaretips #skincareroutine",
            "#beautyhacks #beautytrends #beautytalk",
            "#beautyshop #beautystore #beautybrands",
            "#beautysalon #beautyclinic #beautytreatment",
            "#beautyspecialist #beautydoctor #beautyexpert",
            "#beautyqueen #beautyguru #beautygoals",
            "#beautyskin #beautyface #beautybody"
        ],
        electronics: [
            "#electronics #gadget #technology #tech",
            "#smartphone #laptop #computer #gaming",
            "#gadgets #techie #technews #innovation",
            "#elektronik #teknologi #gadgetmurah",
            "#gadgetindonesia #gadgetoriginal #gadgetbaru",
            "#gadgetstore #gadgetshop #gadgetlife",
            "#gadgetreview #gadgetupdate #gadgettips",
            "#gadgetlovers #gadgetaddict #gadgetmania",
            "#smartphonephotography #smartphonereview",
            "#laptopmurah #laptopgaming #laptopbaru",
            "#komputermurah #komputergaming #komputer",
            "#gaminggear #gamingsetup #gamingpc",
            "#gaminglife #gaminglaptop #gamingconsole",
            "#smartwatch #smarttv #smarthome",
            "#wirelessearbuds #bluetoothspeaker #powerbank",
            "#cctv #printer #scanner #monitor",
            "#techreview #techupdate #techblog",
            "#techindonesia #techmurah #techbaru",
            "#techstore #techshop #techlife",
            "#techlover #techaddict #techmania"
        ],
        home: [
            "#homedecor #homedesign #homeliving",
            "#homestyle #homeinterior #homeinspiration",
            "#homeideas #homedecoration #homeaccessories",
            "#homefurniture #homeware #homestuff",
            "#homesweethome #homegarden #homeoffice",
            "#homekitchen #homebathroom #homeorganizer",
            "#homeappliances #homeelectronics #homegadgets",
            "#homeutilities #homeessentials #homestorage",
            "#homemakeover #homerenovation #homeimprovement",
            "#homemaintenance #homecleaning #homecare",
            "#rumahmewah #rumahmewahmurah #rumahmewahminimalis",
            "#rumahmewahmodern #rumahmewahklasik #rumahmewahidaman",
            "#dekorasirumah #dekorasikamar #dekorasiruangtamu",
            "#dekorasikamaranak #dekorasikamarminimalis",
            "#perabotanrumah #perabotanrumahtangga",
            "#perabotanminimalis #perabotanmodern",
            "#perabotankayu #perabotanjati #perabotanrotan",
            "#perabotanmurah #perabotanbaru #perabotanantik",
            "#alatrumahtangga #alatdapur #alatmasak",
            "#alatkebersihan #alatkamar #alatmandi"
        ],
        baby: [
            "#baby #babyshop #babystuff #babygear",
            "#babycare #babyessentials #babynecessities",
            "#babyproducts #babyitems #babygoods",
            "#babyfashion #babyclothes #babyoutfit",
            "#babyaccessories #babyshoes #babysocks",
            "#babyfood #babyfeeding #babymeal",
            "#babytoys #babyplay #babylearn",
            "#babyhealth #babysafety #babyprotection",
            "#babydiaper #babywipes #babybath",
            "#babyshampoo #babysoap #babylotion",
            "#perlengkapanbayi #kebutuhanbayi #alatbayi",
            "#bajubayi #celanababyi #topibayi",
            "#sepatubayi #kauskakinbayi #aksesorisbayi",
            "#makananbayi #mpasi #mpasiorganik",
            "#mpasihomemade #mpasisehat #mpasimenu",
            "#mainanbayi #mainanedukasi #mainananak",
            "#kesehatanbayi #perawatanbayi #perlindunganbayi",
            "#popokbayi #tisuebayi #sabunbayi",
            "#sampobayi #lotionbayi #minyakbayi",
            "#bedongbayi #selimutbayi #gendonganbayi"
        ],
        automotive: [
            "#automotive #otomotif #mobil #motor",
            "#mobilbekas #mobilbaru #mobilmodifikasi",
            "#motorbekas #motorbaru #motormodifikasi",
            "#sparepart #onderdil #aksesorismobil",
            "#aksesorismotor #bengkel #montir",
            "#mobilantik #mobilclassic #mobilsport",
            "#motorantik #motorclassic #motorsport",
            "#mobillistrik #motorlistrik #evehicle",
            "#mobilhybrid #motorhybrid #hybrid",
            "#mobiloffroad #motoroffroad #offroad",
            "#mobilracing #motorracing #racing",
            "#mobilmodif #motormodif #modifikasi",
            "#mobilcustom #motorcustom #custom",
            "#mobilvelg #motorvelg #velgracing",
            "#mobilaudio #motoraudio #audiocar",
            "#mobilinterior #motorinterior #interior",
            "#mobilexterior #motorexterior #exterior",
            "#mobilperformance #motorperformance #performance",
            "#mobiltuning #motortuning #tuning",
            "#mobilwrap #motorwrap #wrapping"
        ],
        jewelry: [
            "#jewelry #accessories #fashion #style",
            "#jewelrydesign #jewelrymaking #jewelrylover",
            "#perhiasan #aksesoris #perhiasanwanita",
            "#perhiasanemas #perhiasanperak #perhiasanmurah",
            "#gelang #kalung #cincin #anting",
            "#goldjewelry #silverjewelry #fashionjewelry",
            "#jewelryshop #jewelrystore #jewelrygram",
            "#handmadejewelry #customjewelry #uniquejewelry",
            "#perhiasanhandmade #perhiasancustom #perhiasanunik",
            "#perhiasanmodern #perhiasantrendi #perhiasankekinian",
            "#perhiasanweddingring #perhiasancouple #perhiasannikah",
            "#perhiasanpremium #perhiasanmewah #perhiasanelegan",
            "#perhiasanfashion #perhiasanwanita #perhiasancantik",
            "#perhiasanoriginal #perhiasanauthentik #perhiasanasli",
            "#perhiasanberkualitas #perhiasanterpercaya #perhiasanaman",
            "#tokoemas #tokoperhiasan #tokojewelry",
            "#jualperhiasan #jualjewelry #jualaksesoris",
            "#perhiasanmutiara #perhiasanberlian #perhiasanpermata",
            "#perhiasanset #perhiasankoleksi #perhiasanlengkap",
            "#perhiasanresmi #perhiasanbergaransi #perhiasanori"
        ],
        watches: [
            "#watch #timepiece #watches #horology",
            "#watchesofinstagram #watchfam #watchcollector",
            "#jamtangan #jamtanganoriginal #jamtanganmurah",
            "#jamtangankeren #jamtangancasio #jamtanganfossil",
            "#jamtanganpria #jamtanganwanita #jamtangancouple",
            "#luxurywatch #watchlover #watchaddict",
            "#watchoftheday #watchstyle #watchmania",
            "#jamtangansport #jamtanganfashion #jamtangandigital",
            "#jamtangananalog #jamtangansmartwatch #jamtanganlimited",
            "#jamtanganmewah #jamtanganpremium #jamtanganunik",
            "#jamtanganbrand #jamtanganbergaransi #jamtanganresmi",
            "#jamtangancasual #jamtanganbisnis #jamtanganformal",
            "#jamtangananak #jamtanganremaja #jamtangandewasa",
            "#jamtanganelektronik #jamtanganmekanik #jamtanganautomatic",
            "#jamtanganchronograph #jamtangandiving #jamtanganmilitary",
            "#tokojamtangan #jualjamtangan #koleksijamtangan",
            "#jamtanganbaru #jamtanganbekas #jamtangansecond",
            "#jamtanganswiss #jamtanganjepang #jamtangankorea",
            "#jamtanganantik #jamtanganvintage #jamtanganklasik",
            "#jamtangantrendi #jamtangankekinian #jamtanganhits"
        ],
        shoes: [
            "#shoes #footwear #sneakers #boots",
            "#shoestyle #shoefashion #shoeaddict",
            "#sepatu #sepatumurah #sepatuoriginal",
            "#sepatunike #sepatuadidas #sepatupuma",
            "#sepatucasual #sepatusport #sepatuformal",
            "#sepatupria #sepatuwanita #sepatuanak",
            "#sepatulari #sepatubasket #sepatufutsal",
            "#sepatuheels #sepatuwedges #sepatuflat",
            "#sepatuboot #sepatusneakers #sepatusandal",
            "#sepatukerja #sepatusekolah #sepatupesta",
            "#sepatukeren #sepatubagus #sepatumewah",
            "#sepatubranded #sepatubrand #sepatuimport",
            "#sepatulokal #sepatuhandmade #sepatucustom",
            "#sepatutrendi #sepatukekinian #sepatuhits",
            "#sepatulimited #sepatuedisi #sepatuspesial",
            "#sepatukulit #sepatukanvas #sepatusuede",
            "#sepatusport #sepatugym #sepatutraining",
            "#sepatujogging #sepatuvolley #sepatubadminton",
            "#sepatugunung #sepatuoutdoor #sepatuadventure",
            "#sepatusafety #sepatukerja #sepatuproyek"
        ],
        bags: [
            "#bags #handbags #purse #wallet",
            "#bagshop #bagsaddict #bagslover",
            "#tas #tasmurah #tasoriginal",
            "#tasbranded #tasbrandedmurah #tasimport",
            "#tashermes #taschanel #tasgucci",
            "#tasransel #tasselempang #taspunggung",
            "#taskoper #taslaptop #taskantor",
            "#tassekolah #taskuliah #tassantai",
            "#taswanita #taspria #tasanak",
            "#tasfashion #tascasual #tasformal",
            "#taskulit #taskanvas #tassuede",
            "#tashandmade #tascustom #tasunik",
            "#taskeren #tasbagus #tasmewah",
            "#tastrendi #taskekinian #tashits",
            "#taslimited #tasedisi #tasspesial",
            "#taslokal #tasindonesia #tashandmade",
            "#tasbatam #taskorea #tasjepang",
            "#taskerja #tassantai #taspesta",
            "#tasgrosir #taseceran #tasreseller",
            "#tasdiskon #taspromo #tassale"
        ],
        pets: [
            "#pets #petsofinstagram #petstagram #petslife",
            "#petslovers #petshop #petscare #petsfood",
            "#hewanpeliharaan #anjing #kucing #kelinci",
            "#petsupplies #petaccessories #petgrooming",
            "#petfood #petshop #petstuff #petcare",
            "#petsitter #pethotel #petdaycare #petclinic",
            "#petvet #pethealth #petmedicine #petvitamin",
            "#petbed #pettoys #petclothes #petfashion",
            "#pettraining #petbehavior #peteducation",
            "#petadoption #petrescue #petshelter",
            "#kucingpersia #kucingdomestik #kucinganggora",
            "#anjingherder #anjinghusky #anjingpoodle",
            "#kelincilokal #kelincihias #kelincianggora",
            "#makanananjing #makanankucing #makanankelinci",
            "#perlengkapanhewan #aksesorishewan #peralatanhewan",
            "#perawatanhewan #grominghewan #salongroom",
            "#klinikehewan #dokerhewan #obathewan",
            "#mainananjing #mainankucing #mainankelinci",
            "#kandanganjing #kandangkucing #kandangkelinci",
            "#petindonesia #petsjakarta #petsbandung"
        ],
        toys: [
            "#toys #mainan #permainan #game",
            "#mainananakanak #mainanedukasi #mainananak",
            "#mainanbaby #mainanbayi #mainanbalita",
            "#mainankayu #mainanplastik #mainanremote",
            "#mainanrobot #mainanmobil #mainanmotor",
            "#mainanpuzzle #mainanlego #mainanboneka",
            "#mainanedukatif #mainankreatif #mainaninteraktif",
            "#mainansensori #mainanmontessori #mainanpaud",
            "#mainananakmurah #mainanmurah #mainanoriginal",
            "#mainanimport #mainanlokal #mainanindo",
            "#mainanbaru #mainanbekas #mainansecond",
            "#mainanlengkap #mainankeren #mainanbagus",
            "#mainanseru #mainanasik #mainanlucu",
            "#mainananakcerdas #mainanpintar #mainansehat",
            "#mainananakmuslim #mainanislami #mainanhalal"
        ],
        stationery: [
            "#stationery #alattulismenulis #atm",
            "#stationeryaddict #stationerylover #stationerymurah",
            "#alattuliskantor #alattulistoko #alattulissekolah",
            "#pulpen #pensil #spidol #marker",
            "#bukutulis #notebook #diary #journal",
            "#kertas #paper #papercraft #scrapbook",
            "#stiker #selotip #lem #gunting",
            "#penghapus #rautan #tipex #correction",
            "#penggaris #jangka #busur #matematika",
            "#map #folder #ordner #fileholder",
            "#stationeryshop #stationerystore #tokostationery",
            "#stationerymurah #stationeryoriginal #stationeryimport",
            "#stationerylokal #stationeryhandmade #stationerycustom",
            "#stationeryset #stationerypack #stationerybundle",
            "#stationerykids #stationeryschool #stationeryoffice"
        ],
        music: [
            "#music #musik #lagu #song",
            "#alatmusik #instrumentmusik #musikalat",
            "#gitar #piano #drum #bass",
            "#biola #saxophone #trumpet #flute",
            "#keyboard #synthesizer #midi #digital",
            "#musikakustik #musikelektrik #musikdigital",
            "#musikklasik #musikjazz #musikpop #musikrock",
            "#musikdangdut #musikmelayu #musiketnik",
            "#musikreligi #musikislami #musikrohani",
            "#musikanak #musikremaja #musikdewasa",
            "#musikindonesia #musiklokal #musikmancanegara",
            "#musiktradisional #musikmodern #musikfusion",
            "#musikstudio #studiomusik #studiorekaman",
            "#musiksekolah #kursusmusik #lesmusik",
            "#musikevent #konser #pertunjukan #show"
        ],
        books: [
            "#books #reading #bookstagram #booklover",
            "#buku #bukumurah #bukuoriginal #bukubaru",
            "#bukubekas #bukuimport #bukulangka",
            "#bukubestseller #bukunovel #bukucerita",
            "#bukuanak #bukuremaja #bukudewasa",
            "#bukupelajaran #bukusekolah #bukukuliah",
            "#bukuagama #bukumotivasi #bukubisnis",
            "#bukumasak #bukuresep #bukukesehatan",
            "#bukuhobi #bukuseni #bukumusik",
            "#bukudigital #ebookindonesia #audiobook",
            "#perpustakaan #tokobuku #gramedia",
            "#bacabuku #hobibaca #komuniasbaca",
            "#resensi #reviewbuku #ulasanbuku",
            "#penulis #penulisbuku #penerbit",
            "#novelremaja #noveldewasa #novelromantis"
        ],
        pets: [
            "#pets #petsofinstagram #petstagram #petslife",
            "#petslovers #petshop #petscare #petsfood",
            "#hewanpeliharaan #anjing #kucing #kelinci",
            "#petsupplies #petaccessories #petgrooming",
            "#petfood #petshop #petstuff #petcare",
            "#petsitter #pethotel #petdaycare #petclinic",
            "#petvet #pethealth #petmedicine #petvitamin",
            "#petbed #pettoys #petclothes #petfashion",
            "#pettraining #petbehavior #peteducation",
            "#petadoption #petrescue #petshelter",
            "#kucingpersia #kucingdomestik #kucinganggora",
            "#anjingherder #anjinghusky #anjingpoodle",
            "#kelincilokal #kelincihias #kelincianggora",
            "#makanananjing #makanankucing #makanankelinci",
            "#perlengkapanhewan #aksesorishewan #peralatanhewan"
        ]
    },
    languageStyles: {
        casual: {
            prefix: [
                "Hai kak! 👋",
                "Halo semuanya! ✨",
                "Hey guys! 🔥",
                "Psst! Ada info nih! 🤫"
            ],
            connectors: [
                "Nah, yang bikin spesial nih...",
                "Mau tau kenapa harus punya?",
                "Ini dia keunggulannya...",
                "Yang bikin beda adalah..."
            ],
            closing: [
                "Buruan order ya! 🏃‍♂️",
                "Jangan sampai kehabisan! 🔥",
                "Yuk kepoin sekarang! 👆",
                "Gas checkout! 🚀"
            ]
        },
        formal: {
            prefix: [
                "Perhatian",
                "Pengumuman",
                "Informasi Produk",
                "Penawaran Khusus"
            ],
            connectors: [
                "Berikut keunggulan produk:",
                "Spesifikasi produk meliputi:",
                "Produk ini memiliki kelebihan:",
                "Fitur unggulan produk:"
            ],
            closing: [
                "Silakan melakukan pemesanan",
                "Segera lakukan pembelian",
                "Hubungi kami untuk pemesanan",
                "Terima kasih atas perhatiannya"
            ]
        },
        persuasive: {
            prefix: [
                "⚡ KESEMPATAN TERBATAS!",
                "🔥 JANGAN LEWATKAN!",
                "💥 PENAWARAN SPESIAL!",
                "⭐ PRODUK UNGGULAN!"
            ],
            connectors: [
                "Anda pasti tidak ingin melewatkan ini:",
                "Lihat keunggulan luar biasanya:",
                "Mengapa produk ini sangat diminati:",
                "Keistimewaan yang tidak boleh dilewatkan:"
            ],
            closing: [
                "Jangan sia-siakan kesempatan ini!",
                "Segera ambil keputusan sekarang!",
                "Waktu terbatas, bertindak cepat!",
                "Kesempatan tidak datang dua kali!"
            ]
        },
        emotional: {
            prefix: [
                "❤️ IMPIAN JADI NYATA!",
                "✨ TAMPIL BEDA!",
                "💫 SPESIAL UNTUKMU!",
                "🌟 WUJUDKAN KEINGINANMU!"
            ],
            connectors: [
                "Rasakan sensasi istimewanya:",
                "Bayangkan betapa bahagianya:",
                "Nikmati pengalaman luar biasa:",
                "Jadilah yang paling memukau:"
            ],
            closing: [
                "Buat impianmu jadi kenyataan!",
                "Berikan yang terbaik untuk dirimu!",
                "Kamu layak mendapatkannya!",
                "Jadikan momen ini tak terlupakan!"
            ]
        }
    },
    platformTemplates: {
        tiktok: {
            prefix: [
                "🔥 VIRAL DI TIKTOK!",
                "TRENDING DI FYPAGE!",
                "LAGI VIRAL!",
                "BEST SELLER TIKTOK!",
                "RECOMMENDED TIKTOK!"
            ],
            features: [
                "Free Ongkir",
                "Cashback",
                "COD",
                "Garansi 7 Hari",
                "Original 100%",
                "Ready Stock",
                "Fast Response",
                "Pengiriman Cepat"
            ],
            hashtags: [
                "#TiktokShop",
                "#BeliDiTiktok",
                "#TiktokShopping",
                "#TiktokFinds",
                "#TiktokMakeMe",
                "#TiktokViral",
                "#TiktokTrending",
                "#FYP",
                "#ForYourPage",
                "#ProdukViral"
            ]
        },
        shopee: {
            prefix: [
                "🌟 SHOPEE MALL!",
                "PREFERRED SELLER!",
                "STAR SELLER!",
                "SUPER SELLER!",
                "SHOPEE RECOMMENDED!"
            ],
            features: [
                "Free Ongkir Extra",
                "Cashback ShopeePay",
                "COD Available",
                "Garansi Shopee",
                "Original 100%",
                "Ready Stock",
                "Fast Response 24 Jam",
                "Same Day Delivery"
            ],
            hashtags: [
                "#Shopee",
                "#ShopeeMall",
                "#ShopeePay",
                "#ShopeeHaul",
                "#ShopeePicks",
                "#ShopeeFinds",
                "#BeliDiShopee",
                "#ShopeeViral",
                "#ShopeeTrending",
                "#GratisShopeePay"
            ]
        }
    },

    // Fungsi untuk mengacak array
    shuffle: function(array) {
        const shuffled = [...array];
        for (let i = shuffled.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
        }
        return shuffled;
    },

    // Format PAS (Problem-Agitate-Solution)
    pas: {
        problem: [
            "Lelah dengan %product_type% yang cepat rusak?",
            "Bosan dengan %product_type% yang tidak tahan lama?",
            "Kesulitan menemukan %product_type% berkualitas?",
            "Sering kecewa dengan %product_type% yang tidak sesuai harapan?",
            "Bingung mencari %product_type% yang terpercaya?"
        ],
        agitate: [
            "Jangan biarkan masalah ini terus mengganggu Anda!",
            "Sudah saatnya upgrade ke yang lebih berkualitas!",
            "Jangan sia-siakan uang Anda untuk produk yang tidak terjamin!",
            "Hentikan kebiasaan membeli %product_type% asal-asalan!",
            "Kenapa harus puas dengan yang biasa-biasa saja?"
        ],
        solution: [
            "Solusinya ada di sini! %product_name% hadir dengan kualitas premium dan harga terjangkau.",
            "Kenalkan %product_name%, solusi tepat untuk kebutuhan Anda!",
            "Saatnya beralih ke %product_name% - pilihan cerdas untuk Anda!",
            "Temukan perbedaannya dengan %product_name% - kualitas terjamin!",
            "Upgrade ke %product_name% sekarang juga!"
        ]
    },

    // Format Story
    story: {
        opening: [
            "Hai Sobat! Mau cerita sedikit nih tentang pengalaman seru dengan %product_name%",
            "Guys! Baru aja nemuin produk keren yang harus aku share nih!",
            "Sharing pengalaman menarik nih tentang %product_name%",
            "Udah pada tau belum? %product_name% lagi viral banget!",
            "Cerita dikit ya, gimana %product_name% bikin aku jatuh cinta"
        ],
        content: [
            "Awalnya aku ragu, tapi setelah nyoba langsung jatuh cinta! Kualitasnya bener-bener di atas ekspektasi.",
            "Yang bikin special itu bukan cuma kualitasnya, tapi juga value for money nya yang super worth it!",
            "Udah cobain banyak produk sejenis, tapi baru kali ini nemu yang bener-bener sesuai sama yang diharapkan.",
            "Gak nyangka bakal sebagus ini. Pantesan aja banyak yang recommended!",
            "Sekarang udah gak bisa move on, tiap hari pasti kepake terus!"
        ],
        closing: [
            "Penasaran kan? Langsung aja cek linknya ya!",
            "Mau punya juga? Yuk kepoin linknya!",
            "Tertarik? Buruan order sebelum kehabisan!",
            "Gak perlu pikir panjang, langsung aja order!",
            "Jangan sampai nyesel karena kehabisan ya!"
        ]
    },

    // Generate content based on format
    generate: function(productName, category, format, language = 'casual', platform = 'tiktok') {
        const style = this.languageStyles[language];
        const platformTemplate = this.platformTemplates[platform];
        
        let content = '';
        
        // Attention section with language style and platform
        content += this.getRandomItem(style.prefix) + '\n';
        content += this.getRandomItem(platformTemplate.prefix) + '\n\n';
        
        // Interest section
        content += this.getRandomItem(style.connectors) + '\n';
        
        // Desire section - platform features
        content += '✅ ' + this.getRandomItem(platformTemplate.features) + '\n';
        content += '✅ ' + this.getRandomItem(platformTemplate.features) + '\n';
        content += '✅ ' + this.getRandomItem(platformTemplate.features) + '\n';
        
        // Action section
        content += '\n' + this.getRandomItem(style.closing) + '\n';
        content += '%affiliate_link%\n\n';
        
        // Hashtags
        content += this.getRandomItems(platformTemplate.hashtags, 5).join(' ');
        
        return content;
    },

    // Helper function to get random item from array
    getRandomItem: function(array) {
        return array[Math.floor(Math.random() * array.length)];
    },

    getRandomItems: function(array, count) {
        const shuffled = array.sort(() => 0.5 - Math.random());
        return shuffled.slice(0, count);
    },

    // Fungsi untuk generate konten dalam jumlah besar
    generateBulkContent: function(productName, category, format, language, platform, count) {
        let contents = [];
        for (let i = 1; i <= count; i++) {
            const content = this.generate(productName, category, format, language, platform);
            contents.push({
                filename: `product${i}.txt`,
                content: content
            });
        }
        return contents;
    },

    // Fungsi untuk download hasil generate sebagai ZIP
    downloadZip: async function(productName, category, format, language, platform, count) {
        try {
            // Generate konten
            const contents = this.generateBulkContent(productName, category, format, language, platform, count);
            
            // Buat objek ZIP
            const zip = new JSZip();
            
            // Tambahkan file ke ZIP
            contents.forEach(item => {
                zip.file(item.filename, item.content);
            });
            
            // Generate ZIP file
            const zipBlob = await zip.generateAsync({
                type: "blob",
                compression: "DEFLATE",
                compressionOptions: {
                    level: 9
                }
            });
            
            // Buat link download
            const downloadLink = document.createElement('a');
            downloadLink.href = URL.createObjectURL(zipBlob);
            downloadLink.download = `${productName}_contents.zip`;
            
            // Trigger download
            document.body.appendChild(downloadLink);
            downloadLink.click();
            document.body.removeChild(downloadLink);
            
            // Bersihkan URL
            URL.revokeObjectURL(downloadLink.href);
            
            return true;
        } catch (error) {
            console.error('Error generating ZIP:', error);
            return false;
        }
    }
}; 